#!/bin/bash
#SBATCH --account=ACCOUNT_NAME
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gpus-per-task=v100:1
#SBATCH --mem=80G
#SBATCH --time=24:00:00
#SBATCH --job-name=bfn_pusht_real
#SBATCH --output=$PROJECT_ROOT/jobs/logs/%x_%j.out
#SBATCH --error=$PROJECT_ROOT/jobs/logs/%x_%j.err

source /apps/conda/miniforge3/24.11.3/etc/profile.d/conda.sh
conda activate bfn

cd $PROJECT_ROOT
export PYTHONPATH="$PROJECT_ROOT/src/diffusion-policy:$PYTHONPATH"
$HOME/.conda/envs/bfn/bin/python scripts/train_workspace.py --config-name=benchmark_bfn_pusht_real