#!/bin/bash
#SBATCH --account=ACCOUNT_NAME
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gpus-per-task=a100:1
#SBATCH --mem=40G
#SBATCH --time=2:00:00
#SBATCH --job-name=bfn_steps_test
#SBATCH --output=jobs/logs/%x_%j.out
#SBATCH --error=jobs/logs/%x_%j.err

source /apps/conda/miniforge3/24.11.3/etc/profile.d/conda.sh
conda activate bfn

cd "$SLURM_SUBMIT_DIR"

$HOME/.conda/envs/bfn/bin/python -u scripts/test_bfn_steps.py
